acme_hello_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
acme_html_homepage:
    path:     /html/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }