gpx_track_homepage:
    path:     /gpxTrack/create
    defaults: { _controller: GpxTrackBundle:Default:create }

gpx_track_taskexample:
    path:     /gpxTrack/add
    defaults: { _controller: GpxTrackBundle:Default:add }

gpx_track_load:
    path:     /gpxTrack/load/{id}
    defaults: { _controller: GpxTrackBundle:Default:load }

gpx_loaded:
     path:     /gpxTrack/map
     defaults: { _controller: GpxTrackBundle:Default:displayMap }