gpx_track_homepage:
    path:     /gpxTrack/create
    defaults: { _controller: GpxTrackBundle:Default:create }

gpx_track_taskexample:
    path:     /gpxTrack/task
    defaults: { _controller: GpxTrackBundle:Default:new }

gpx_loaded:
     path:     /gpxTrack/map
     defaults: { _controller: GpxTrackBundle:Default:displayMap }